stages:
  - test
  - deploy

test:
  stage: test
  script:
    # the main objective of maxdepth=2 is to ignore other python scripts which are not airflow DAGs
    - export PYTHONPATH=$CI_PROJECT_DIR
    - pip install --user flake8
    - for py in $(find $CI_PROJECT_DIR -maxdepth 0 -name "*.py"); do python3.6 $py; if [ $? != 0 ]; then exit 1; fi; done;
    - python3.6 -m unittest discover -s $CI_PROJECT_DIR -p "*_test.py"
    - flake8 --ignore=E501 .
  tags:
    - onprem

# checkout branch on airflow-dev
deploy:
  stage: deploy
  script:
    - sshpass -p$DEV_PASS ssh -o StrictHostKeyChecking=no $DEV_USER@$DEV_NODE 'cd $AIRFLOW_HOME/dags/'$CI_PROJECT_NAME'; git pull'
    - sshpass -p$DEV_PASS ssh -o StrictHostKeyChecking=no $DEV_USER@$DEV_NODE 'cd $AIRFLOW_HOME/dags/'$CI_PROJECT_NAME'; git checkout '$CI_COMMIT_REF_NAME
    - sshpass -p$DEV_PASS ssh -o StrictHostKeyChecking=no $DEV_USER@$DEV_NODE 'cd $AIRFLOW_HOME/dags/'$CI_PROJECT_NAME'; git reset --hard'
    - sshpass -p$DEV_PASS ssh -o StrictHostKeyChecking=no $DEV_USER@$DEV_NODE 'cd $AIRFLOW_HOME/dags/'$CI_PROJECT_NAME'; git clean -fd'
    - sshpass -p$DEV_PASS ssh -o StrictHostKeyChecking=no $DEV_USER@$DEV_NODE 'cd $AIRFLOW_HOME/dags/'$CI_PROJECT_NAME'; airflow list_dags'
  except:
    - master
  tags:
    - onprem
